openapi: 3.0.3

info:
  title: <<< .ServiceName >>>
  description: Provides API for <<< .ServiceName >>>
  version: 1.0.0

servers:
  - url: /

paths:
  /status:
    get:
      tags:
        - private
      summary: Docker probe for readiness
      responses:
        "200":
          description: OK

  /api-docs:
    get:
      tags:
        - private
      summary: Swagger documentation endpoint
      responses:
        "200":
          description: successful operation
